-- ============================================================================
--  Deacons Service Management — Supabase Backend Schema
--  Run this whole file once in: Supabase Dashboard → SQL Editor → New query → Run
--  Idempotent: safe to re-run.
--
--  NOTE on naming: data-table columns are quoted camelCase to match the Kotlin
--  entity property names EXACTLY (e.g. "fullName", "schoolClass"). This lets the
--  Android app (Moshi) read/write rows with zero entity-annotation changes.
--  Timestamps are bigint (epoch millis) to match the entities' Long fields.
-- ============================================================================

create extension if not exists "pgcrypto";

-- ============================ DATA TABLES ===================================
create table if not exists school_classes (
    "id"          bigint generated by default as identity primary key,
    "name"        text not null,
    "orderIndex"  int  not null default 0,
    "isActive"    boolean not null default true
);

create table if not exists groups (
    "id"          bigint generated by default as identity primary key,
    "name"        text not null,
    "description" text not null default '',
    "isActive"    boolean not null default true,
    "createdAt"   bigint not null default (extract(epoch from now())*1000)::bigint
);

create table if not exists servants (
    "id"        bigint generated by default as identity primary key,
    "name"      text not null,
    "phone"     text not null default '',
    "role"      text not null default 'خادم',
    "isActive"  boolean not null default true
);

create table if not exists members (
    "id"             bigint generated by default as identity primary key,
    "fullName"       text not null,
    "profileImage"   text,
    "schoolClass"    text not null default '',
    "birthDate"      text not null default '',
    "phone"          text not null default '',
    "parentPhone"    text not null default '',
    "governorate"    text not null default 'أسيوط',
    "center"         text not null default 'القوصية',
    "area"           text not null default 'مير',
    "street"         text not null default '',
    "houseNumber"    text not null default '',
    "addressDetails" text not null default '',
    "groupId"        bigint references groups("id") on delete set null,
    "notes"          text not null default '',
    "isActive"       boolean not null default true,
    "createdAt"      bigint not null default (extract(epoch from now())*1000)::bigint,
    "updatedAt"      bigint not null default (extract(epoch from now())*1000)::bigint
);
create index if not exists idx_members_group   on members("groupId");
create index if not exists idx_members_active  on members("isActive");

create table if not exists member_barcodes (
    "id"            bigint generated by default as identity primary key,
    "memberId"      bigint not null references members("id") on delete cascade,
    "barcodeValue"  text not null unique,
    "barcodeFormat" text not null default 'CODE_128',
    "createdAt"     bigint not null default (extract(epoch from now())*1000)::bigint,
    "updatedAt"     bigint not null default (extract(epoch from now())*1000)::bigint
);
create index if not exists idx_barcode_member on member_barcodes("memberId");

create table if not exists visit_records (
    "id"         bigint generated by default as identity primary key,
    "memberId"   bigint not null references members("id") on delete cascade,
    "visitDate"  text not null,
    "notes"      text not null default '',
    "createdAt"  bigint not null default (extract(epoch from now())*1000)::bigint,
    "updatedAt"  bigint not null default (extract(epoch from now())*1000)::bigint
);
create index if not exists idx_visit_member on visit_records("memberId");

create table if not exists attendances (
    "id"          bigint generated by default as identity primary key,
    "memberId"    bigint not null references members("id") on delete cascade,
    "date"        text not null,
    "type"        text not null check ("type" in ('SERVICE','MASS')),
    "massNumber"  int,
    "status"      text not null check ("status" in ('PRESENT','ABSENT','EXCUSED')),
    "notes"       text not null default '',
    unique ("memberId","date","type","massNumber")
);
create index if not exists idx_att_member on attendances("memberId");
create index if not exists idx_att_date   on attendances("date");

create table if not exists hymns (
    "id"              bigint generated by default as identity primary key,
    "name"            text not null,
    "maxScore"        double precision not null default 10.0,
    "category"         text not null default 'عام',
    "durationInDays"  int not null default 30,
    "deadline"        text not null default '',
    "notes"           text not null default '',
    "isActive"        boolean not null default true
);

create table if not exists hymn_assessments (
    "id"         bigint generated by default as identity primary key,
    "memberId"   bigint not null references members("id") on delete cascade,
    "hymnId"     bigint not null references hymns("id") on delete cascade,
    "date"       text not null,
    "score"      double precision not null,
    "maxScore"   double precision not null,
    "notes"      text not null default '',
    "createdAt"  bigint not null default (extract(epoch from now())*1000)::bigint,
    "updatedAt"  bigint not null default (extract(epoch from now())*1000)::bigint,
    unique ("memberId","hymnId")
);

create table if not exists bible_lessons (
    "id"              bigint generated by default as identity primary key,
    "name"            text not null,
    "durationInDays"  int not null default 14,
    "deadline"        text not null default '',
    "notes"           text not null default '',
    "isActive"        boolean not null default true,
    "createdAt"       bigint not null default (extract(epoch from now())*1000)::bigint
);

create table if not exists bible_assessments (
    "id"          bigint generated by default as identity primary key,
    "memberId"    bigint not null references members("id") on delete cascade,
    "date"        text not null,
    "lessonName"  text not null,
    "score"       double precision not null,
    "maxScore"    double precision not null default 10.0,
    "notes"       text not null default '',
    "lessonId"    bigint references bible_lessons("id") on delete set null
);
create index if not exists idx_bible_member on bible_assessments("memberId");

create table if not exists exams (
    "id"              bigint generated by default as identity primary key,
    "name"            text not null,
    "date"            text not null default '',
    "maxScore"        double precision not null default 100.0,
    "durationInDays"  int not null default 7,
    "deadline"        text not null default '',
    "notes"           text not null default '',
    "isActive"        boolean not null default true
);

create table if not exists exam_results (
    "id"        bigint generated by default as identity primary key,
    "examId"    bigint not null references exams("id") on delete cascade,
    "memberId"  bigint not null references members("id") on delete cascade,
    "score"     double precision not null,
    "maxScore"  double precision not null default 100.0,
    "date"      text not null default '',
    "notes"     text not null default ''
);

create table if not exists evaluation_periods (
    "id"                   bigint generated by default as identity primary key,
    "name"                 text not null,
    "startDate"            text not null,
    "endDate"              text not null,
    "requiredMassesCount"  int not null default 2,
    "notes"                text not null default '',
    "isActive"             boolean not null default true
);

create table if not exists app_settings (
    "key"   text primary key,
    "value" text not null default ''
);

-- ======================= APP USERS + ROLES (snake_case) =====================
create table if not exists app_users (
    id          uuid primary key references auth.users(id) on delete cascade,
    email       text not null unique,
    full_name   text not null default '',
    phone       text not null default '',
    role        text not null default 'servant'
                check (role in ('super_admin','admin','servant','viewer')),
    servant_id  bigint references servants("id") on delete set null,
    is_active   boolean not null default false,
    assigned_class text not null default '',
    assigned_classes text[] not null default '{}',
    can_record_attendance boolean not null default false,
    can_record_assessments boolean not null default false,
    can_manage_members boolean not null default false,
    can_export_reports boolean not null default false,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);
-- Keep existing installations compatible when this schema is re-run.
alter table app_users drop constraint if exists app_users_role_check;
alter table app_users add constraint app_users_role_check check (role in ('super_admin','admin','servant','viewer'));
alter table app_users add column if not exists assigned_class text not null default '';
alter table app_users add column if not exists assigned_classes text[] not null default '{}';
update app_users set assigned_classes = case when assigned_class <> '' and cardinality(assigned_classes)=0 then array[assigned_class] else assigned_classes end;
alter table app_users add column if not exists can_record_attendance boolean not null default false;
alter table app_users add column if not exists can_record_assessments boolean not null default false;
alter table app_users add column if not exists can_manage_members boolean not null default false;
alter table app_users add column if not exists can_export_reports boolean not null default false;


create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    insert into public.app_users (id, email, full_name)
    values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name',''))
    on conflict (id) do nothing;
    return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.app_role()
returns text language sql security definer set search_path = public as $$
    select role from public.app_users where id = auth.uid() and is_active = true;
$$;

create or replace function public.is_super_admin()
returns boolean language sql security definer set search_path = public as $$
    select coalesce((select role='super_admin' from public.app_users
                     where id = auth.uid() and is_active = true), false);
$$;

create or replace function public.is_admin()
returns boolean language sql security definer set search_path = public as $$
    select coalesce((select role in ('super_admin','admin') from public.app_users
                     where id = auth.uid() and is_active = true), false);
$$;

create or replace function public.user_assigned_classes()
returns text[] language sql security definer set search_path = public as $$
    select coalesce((select assigned_classes from public.app_users
                     where id = auth.uid() and is_active = true), '{}');
$$;

create or replace function public.user_has_class(class_name text)
returns boolean language sql security definer set search_path = public as $$
    select public.is_admin() or class_name = any(public.user_assigned_classes());
$$;

create or replace function public.has_permission(permission text)
returns boolean language plpgsql security definer set search_path = public as $$
declare
    u public.app_users%rowtype;
begin
    select * into u from public.app_users where id = auth.uid() and is_active = true;
    if u.id is null then return false; end if;
    if u.role in ('super_admin','admin') then return true; end if;
    if u.role <> 'servant' then return false; end if;
    case permission
        when 'attendance' then return coalesce(u.can_record_attendance, false);
        when 'assessments' then return coalesce(u.can_record_assessments, false);
        when 'members' then return coalesce(u.can_manage_members, false);
        when 'reports' then return coalesce(u.can_export_reports, false);
        else return false;
    end case;
end; $$;

-- ============================== RLS =========================================
alter table school_classes    enable row level security;
alter table groups            enable row level security;
alter table servants          enable row level security;
alter table members           enable row level security;
alter table member_barcodes   enable row level security;
alter table visit_records     enable row level security;
alter table attendances       enable row level security;
alter table hymns             enable row level security;
alter table hymn_assessments  enable row level security;
alter table bible_lessons     enable row level security;
alter table bible_assessments enable row level security;
alter table exams             enable row level security;
alter table exam_results      enable row level security;
alter table evaluation_periods enable row level security;
alter table app_settings      enable row level security;
alter table app_users         enable row level security;

-- READ: any active app user (admin/servant/viewer)
drop policy if exists "read_all" on school_classes;
create policy "read_all" on school_classes for select using ((public.is_admin() or public.app_role() = 'viewer') or (public.app_role() = 'servant' and public.user_has_class("name")));
drop policy if exists "read_all" on groups;
create policy "read_all" on groups             for select using (public.app_role() is not null);
drop policy if exists "read_all" on servants;
create policy "read_all" on servants           for select using (public.app_role() is not null);
drop policy if exists "read_all" on members;
create policy "read_all" on members for select using (
    (public.is_admin() or public.app_role() = 'viewer')
    or (public.app_role() = 'servant' and public.user_has_class("schoolClass"))
);
drop policy if exists "read_all" on member_barcodes;
create policy "read_all" on member_barcodes for select using (
    (public.is_admin() or public.app_role() = 'viewer')
    or (public.app_role() = 'servant' and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")))
);
drop policy if exists "read_all" on visit_records;
create policy "read_all" on visit_records for select using (
    (public.is_admin() or public.app_role() = 'viewer')
    or (public.app_role() = 'servant' and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")))
);
drop policy if exists "read_all" on attendances;
create policy "read_all" on attendances for select using (
    (public.is_admin() or public.app_role() = 'viewer')
    or (public.app_role() = 'servant' and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")))
);
drop policy if exists "read_all" on hymns;
create policy "read_all" on hymns              for select using (public.app_role() is not null);
drop policy if exists "read_all" on hymn_assessments;
create policy "read_all" on hymn_assessments for select using (
    (public.is_admin() or public.app_role() = 'viewer')
    or (public.app_role() = 'servant' and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")))
);
drop policy if exists "read_all" on bible_lessons;
create policy "read_all" on bible_lessons      for select using (public.app_role() is not null);
drop policy if exists "read_all" on bible_assessments;
create policy "read_all" on bible_assessments for select using (
    (public.is_admin() or public.app_role() = 'viewer')
    or (public.app_role() = 'servant' and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")))
);
drop policy if exists "read_all" on exams;
create policy "read_all" on exams              for select using (public.app_role() is not null);
drop policy if exists "read_all" on exam_results;
create policy "read_all" on exam_results for select using (
    (public.is_admin() or public.app_role() = 'viewer')
    or (public.app_role() = 'servant' and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")))
);
drop policy if exists "read_all" on evaluation_periods;
create policy "read_all" on evaluation_periods for select using (public.app_role() is not null);
drop policy if exists "read_all" on app_settings;
create policy "read_all" on app_settings      for select using (public.app_role() is not null);

-- ADMIN: full write on all data tables
drop policy if exists "admin_write" on school_classes;
create policy "admin_write" on school_classes     for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on groups;
create policy "admin_write" on groups             for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on servants;
create policy "admin_write" on servants           for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on members;
create policy "admin_write" on members            for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on member_barcodes;
create policy "admin_write" on member_barcodes     for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on visit_records;
create policy "admin_write" on visit_records      for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on attendances;
create policy "admin_write" on attendances        for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on hymns;
create policy "admin_write" on hymns              for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on hymn_assessments;
create policy "admin_write" on hymn_assessments   for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on bible_lessons;
create policy "admin_write" on bible_lessons      for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on bible_assessments;
create policy "admin_write" on bible_assessments   for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on exams;
create policy "admin_write" on exams               for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on exam_results;
create policy "admin_write" on exam_results        for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on evaluation_periods;
create policy "admin_write" on evaluation_periods for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin_write" on app_settings;
create policy "admin_write" on app_settings       for all using (public.is_admin()) with check (public.is_admin());

-- SERVANT: writes are controlled by the permissions assigned in app_users.
drop policy if exists "servant_write_members" on members;
create policy "servant_write_members" on members for all
    using (public.has_permission('members') and public.user_has_class("schoolClass"))
    with check (public.has_permission('members') and public.user_has_class("schoolClass"));
drop policy if exists "servant_write_attendance" on attendances;
create policy "servant_write_attendance" on attendances for all
    using (public.has_permission('attendance') and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")))
    with check (public.has_permission('attendance') and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")));
drop policy if exists "servant_write_barcode" on member_barcodes;
create policy "servant_write_barcode" on member_barcodes for all
    using (public.has_permission('members') and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")))
    with check (public.has_permission('members') and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")));
drop policy if exists "servant_write_visits" on visit_records;
create policy "servant_write_visits" on visit_records for all
    using (public.has_permission('members') and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")))
    with check (public.has_permission('members') and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")));
drop policy if exists "servant_write_hymn_ass" on hymn_assessments;
create policy "servant_write_hymn_ass" on hymn_assessments for all
    using (public.has_permission('assessments') and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")))
    with check (public.has_permission('assessments') and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")));
drop policy if exists "servant_write_bible_ass" on bible_assessments;
create policy "servant_write_bible_ass" on bible_assessments for all
    using (public.has_permission('assessments') and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")))
    with check (public.has_permission('assessments') and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")));
drop policy if exists "servant_write_exam_res" on exam_results;
create policy "servant_write_exam_res" on exam_results for all
    using (public.has_permission('assessments') and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")))
    with check (public.has_permission('assessments') and exists (select 1 from members m where m."id" = "memberId" and public.user_has_class(m."schoolClass")));

-- app_users: admins can read/manage servants/viewers; only Super Admin can manage admins.
drop policy if exists "admin_only_users" on app_users;
drop policy if exists "read_self" on app_users;
drop policy if exists "admin_read_users" on app_users;
drop policy if exists "admin_manage_users" on app_users;
drop policy if exists "super_admin_manage_users" on app_users;
create policy "admin_read_users" on app_users for select using (public.is_admin());
create policy "read_self" on app_users for select using (id = auth.uid());
create policy "admin_manage_users" on app_users for update
    using (public.is_admin() and role not in ('super_admin','admin'))
    with check (public.is_admin() and role not in ('super_admin','admin'));
create policy "super_admin_manage_users" on app_users for all
    using (public.is_super_admin()) with check (public.is_super_admin());

-- ============================ STORAGE (photos) =============================
insert into storage.buckets (id, name, public) values ('member-photos','member-photos', true)
on conflict (id) do nothing;

drop policy if exists "photos_read" on storage.objects;
create policy "photos_read" on storage.objects for select
    using (bucket_id = 'member-photos' and auth.role() = 'authenticated');
drop policy if exists "photos_write" on storage.objects;
create policy "photos_write" on storage.objects for insert
    with check (bucket_id = 'member-photos' and public.app_role() is not null);
drop policy if exists "photos_update" on storage.objects;
create policy "photos_update" on storage.objects for update
    using (bucket_id = 'member-photos' and public.app_role() is not null);
drop policy if exists "photos_delete" on storage.objects;
create policy "photos_delete" on storage.objects for delete
    using (bucket_id = 'member-photos' and public.is_admin());

-- ============================== SEED DATA ==================================
-- Prevent duplicate seed classes when this script is re-run.
delete from school_classes a using school_classes b
where a."name" = b."name" and a."id" > b."id";
create unique index if not exists uq_school_classes_name on school_classes("name");

insert into school_classes ("name","orderIndex") values
    ('أولى ابتدائي',0),('ثانية ابتدائي',1),('ثالثة ابتدائي',2),
    ('رابعة ابتدائي',3),('خامسة ابتدائي',4),('سادسة ابتدائي',5),
    ('أولى إعدادي',6),('ثانية إعدادي',7),('ثالثة إعدادي',8),
    ('أولى ثانوي',9),('ثانية ثانوي',10),('ثالثة ثانوي',11)
on conflict ("name") do nothing;

insert into app_settings ("key","value") values
    ('service_attendance_target','4'),
    ('service_ministry_attendance_target','4'),
    ('overdue_attendance_absence_days','4'),
    ('overdue_hymn_days','30'),
    ('overdue_bible_days','14'),
    ('overdue_exam_days','7'),
    ('notifications_enabled','true')
on conflict ("key") do nothing;

-- Server-side timestamps for conflict-safe synchronization.
create or replace function public.touch_members_updated_at()
returns trigger language plpgsql as $$ begin new."updatedAt"=(extract(epoch from now())*1000)::bigint; return new; end; $$;
drop trigger if exists trg_members_updated_at on members;
create trigger trg_members_updated_at before update on members for each row execute function public.touch_members_updated_at();

create or replace function public.touch_member_barcodes_updated_at()
returns trigger language plpgsql as $$ begin new."updatedAt"=(extract(epoch from now())*1000)::bigint; return new; end; $$;
drop trigger if exists trg_member_barcodes_updated_at on member_barcodes;
create trigger trg_member_barcodes_updated_at before update on member_barcodes for each row execute function public.touch_member_barcodes_updated_at();

create or replace function public.touch_visit_records_updated_at()
returns trigger language plpgsql as $$ begin new."updatedAt"=(extract(epoch from now())*1000)::bigint; return new; end; $$;
drop trigger if exists trg_visit_records_updated_at on visit_records;
create trigger trg_visit_records_updated_at before update on visit_records for each row execute function public.touch_visit_records_updated_at();

create or replace function public.touch_hymn_assessments_updated_at()
returns trigger language plpgsql as $$ begin new."updatedAt"=(extract(epoch from now())*1000)::bigint; return new; end; $$;
drop trigger if exists trg_hymn_assessments_updated_at on hymn_assessments;
create trigger trg_hymn_assessments_updated_at before update on hymn_assessments for each row execute function public.touch_hymn_assessments_updated_at();

-- app_users updated_at auto-touch (snake_case table)
create or replace function public.touch_app_users_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists trg_app_users_touch on app_users;
create trigger trg_app_users_touch before update on app_users
    for each row execute function public.touch_app_users_updated_at();

-- ============================================================================
--  ADMIN BOOTSTRAP
--  The Android app creates Auth users. After the first Auth user exists, this
--  idempotent statement promotes the owner account to Super Admin.
--  Never place a service_role key in the Android app.
-- ============================================================================

update public.app_users
set role = 'super_admin', is_active = true,
    can_record_attendance = true, can_record_assessments = true,
    can_manage_members = true, can_export_reports = true, updated_at = now()
where email = 'abramonetwo@gmail.com';
